version: '3.8'

services:
  frontend:
    image: piyushdg/ui:latest
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER_URL=http://3.112.217.232:8080/employees
  
  backend:
    image: piyushdg/be:latest
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - ALLOWED_ORIGINS=*
  db:
    image: postgres:13
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

